# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import external_coordinator_pb2 as external__coordinator__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in external_coordinator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ExternalCoordinatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterMissionControl = channel.unary_unary(
                '/ecrpc.ExternalCoordinator/RegisterMissionControl',
                request_serializer=external__coordinator__pb2.RegisterMissionControlRequest.SerializeToString,
                response_deserializer=external__coordinator__pb2.RegisterMissionControlResponse.FromString,
                _registered_method=True)
        self.QueryAggregatedMissionControl = channel.unary_stream(
                '/ecrpc.ExternalCoordinator/QueryAggregatedMissionControl',
                request_serializer=external__coordinator__pb2.QueryAggregatedMissionControlRequest.SerializeToString,
                response_deserializer=external__coordinator__pb2.QueryAggregatedMissionControlResponse.FromString,
                _registered_method=True)


class ExternalCoordinatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterMissionControl(self, request, context):
        """RegisterMissionControl registers mission control data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAggregatedMissionControl(self, request, context):
        """QueryAggregatedMissionControl queries aggregated mission control data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExternalCoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterMissionControl': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterMissionControl,
                    request_deserializer=external__coordinator__pb2.RegisterMissionControlRequest.FromString,
                    response_serializer=external__coordinator__pb2.RegisterMissionControlResponse.SerializeToString,
            ),
            'QueryAggregatedMissionControl': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryAggregatedMissionControl,
                    request_deserializer=external__coordinator__pb2.QueryAggregatedMissionControlRequest.FromString,
                    response_serializer=external__coordinator__pb2.QueryAggregatedMissionControlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ecrpc.ExternalCoordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExternalCoordinator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterMissionControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecrpc.ExternalCoordinator/RegisterMissionControl',
            external__coordinator__pb2.RegisterMissionControlRequest.SerializeToString,
            external__coordinator__pb2.RegisterMissionControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAggregatedMissionControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ecrpc.ExternalCoordinator/QueryAggregatedMissionControl',
            external__coordinator__pb2.QueryAggregatedMissionControlRequest.SerializeToString,
            external__coordinator__pb2.QueryAggregatedMissionControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
